import { ReactNode } from "react";
import { Providers } from "@/redux/provider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "../styles/index.scss";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Node Talents",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextTopLoader color="#cddbcb" />
        <Providers>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          limit={3}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
        {children}
          </Providers>
      </body>
    </html>
  );
}
